blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PagesList.as_view(), name='pages'),
    path("crear/", views.PageCreate.as_view(), name="page_create"),
    path('<int:pk>', views.PageDetail.as_view(), name='page_detail'),
    path('<int:pk>/editar', views.PageEdit.as_view(), name='page_edit'),
    path('<int:pk>/borrar', views.PageDelete.as_view(), name='page_delete'),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('index.urls')),
    path('entretenimiento/', include('entretenimiento.urls')),
    path('accounts/', include('accounts.urls')),
    path('pages/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
# Create your models here.

class Page(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100)
    image_page = models.ImageField(upload_to='blog/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = RichTextField(blank=True, null=True)
    datetimecreation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from . import models

class PageForm(forms.ModelForm):
    class Meta:
        model = models.Page
        fields = ['title', 'subtitle', 'author', 'image_page', 'content']
        

blog/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic import ListView
from .models import Page
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class PagesList(ListView):
    model = Page
    template_name = 'blog/pages_list.html'

class PageCreate(LoginRequiredMixin, CreateView):
        model = Page
        fields = ['title', 'subtitle', 'author', 'image_page', 'content']
        success_url = '/pages/'

class PageDetail(DetailView):
    model = Page
    template_name = 'blog/detail_page.html'

class PageEdit(LoginRequiredMixin, UpdateView):
    model = Page
    success_url = '/pages/'
    fields = ['title', 'subtitle', 'author', 'image_page', 'content']
    template_name = 'blog/edit_page.html'
    
class PageDelete(LoginRequiredMixin, DeleteView):
    model = Page
    success_url = '/pages/'

blog/templates/blog/detail_page.html
{% extends 'index/index.html' %}


{% block header_block %}
    <div style='display: felx; background-color: #212529;'>
        <h1 style='justify-content: center; color: #fff; padding: 2rem; margin: 0;'>DETAILS</h1>
    </div>
    <div style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M-95.65,35.05 C144.74,263.98 442.15,-48.83 526.80,134.72 L500.00,0.00 L0.00,0.00 Z" style="stroke: none; fill: #212529;"></path></svg></div>
{% endblock header_block %}


{% block body_block %}
    <div style='width:100rem; margin:0 auto; padding: 1rem; '>
        <div style='background: #E0EDFC; padding: 4rem; border-radius: 1rem;'>
            <p>
                <a href={% url 'pages' %} style='padding: 1rem;'><i class="bi bi-arrow-bar-left"></i> volver</a>
            </p>

            <p>
                <li>{{page.title}}</li>
                <li>{{page.subtitle}}</li>
                <li>{{page.author}}</li>
                {% if page.image_page %}
                    <img src="{{page.image_page.url}}" alt="image" height="70"> <br>
                {% endif %}
                <li>{{page.content | safe }}</li>
                <li>{{page.datetimecreation | date:'d-m-Y H:m'}}</li>
            </p>
        </div>
    </div>
{% endblock body_block %}

blog/templates/blog/edit_page.html
{% extends 'index/index.html' %}

{% block header_block %}
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            {% block header_text_block %}
                                <h1 class="display-5 fw-bolder text-white mb-2">ADD AN ITEM</h1>
                            {% endblock header_text_block %}
                            <p class="lead text-white-50 mb-4"></p>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock header_block %}

{% block body_block %}
    <div style='width:90rem; margin:0 auto; padding: 2rem; '>
        <div style='background: #E0EDFC; padding: 3rem; border-radius: 1rem;'>
            <p>
                <a href={% url 'pages' %} style='padding: 1rem;'><i class="bi bi-arrow-bar-left"></i> volver</a>
            </p>
            <form action="" method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                <table>
                    {{form.media}}
                    {{form.as_p}}
                </table>
                <input type="submit" value='Actualizar'>
            </form>
        </div>
    </div>
{% endblock body_block %}

blog/templates/blog/page_confirm_delete.html
{% extends 'index/index.html' %}


{% block header_block %}
    <div style='display: felx; background-color: #212529;'>
        <h1 style='justify-content: center; color: #fff; padding: 2rem; margin: 0;'>DELETE AN ITEM</h1>
    </div>
    <div style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M-95.65,35.05 C144.74,263.98 442.15,-48.83 526.80,134.72 L500.00,0.00 L0.00,0.00 Z" style="stroke: none; fill: #212529;"></path></svg></div>
{% endblock header_block %}

{% block body_block %}

    <div style='width:90rem; margin:0 auto; padding: 2rem; '>
        <div style='background: #E0EDFC; padding: 3rem; border-radius: 1rem;'>
            <p>
                <a href={% url 'pages' %} style='padding: 1rem;'><i class="bi bi-arrow-bar-left"></i> volver</a>
            </p>
            
            <form action='' method='post'>
                {% csrf_token %}
                Esta seguro de que quiere eliminar el articulo, {{object}}?<br><br><br>
                <input style='padding: 1rem 3rem; margin: 1rem;' type="submit" value='Borrar'>
            </form>
        </div>
    </div>
{% endblock body_block %}

blog/templates/blog/page_form.html
{% extends 'index/index.html' %}

{% block header_block %}
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            {% block header_text_block %}
                                <h1 class="display-5 fw-bolder text-white mb-2">ADD AN ITEM</h1>
                            {% endblock header_text_block %}
                            <p class="lead text-white-50 mb-4"></p>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock header_block %}

{% block body_block %}
    <div style='width:50rem; margin:0 auto; '>
        <div style='background: #E0EDFC; padding: 1rem 60rem 1rem 1rem; border-radius: 1rem; margin: 3rem'>
            <p>
                <a href={% url 'pages' %} style='padding: 1rem;'><i class="bi bi-arrow-bar-left"></i> volver</a>
            </p>
            <form action={% url 'page_create' %} method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                <table>
                    {{form.media}}
                    {{form.as_p}}
                </table>
                <input type="submit" value='Agregar'>
            </form>
        </div>
    </div>
{% endblock body_block %}

blog/templates/blog/pages_list.html
{% extends 'index/index.html' %}

{% block header_block %}
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            {% block header_text_block %}
                                <h1 class="display-5 fw-bolder text-white mb-2">PAGES</h1>
                            {% endblock header_text_block %}
                            <p class="lead text-white-50 mb-4"></p>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock header_block %}

{% block body_block %}
    <div style='width:65rem; margin:0 auto; padding: 1rem; '>
        <div style='background: #E0EDFC; padding: 2rem; border-radius: 1rem;'>
            <a href={% url 'page_create' %}>Crear articulo</a>

        {% for page in page_list %}
            <ul>
                <li>{{page.title}}<br>
                    {% if page.image_page %}
                        <img src="{{page.image_page.url}}" alt="image" height="70"><br>
                    {% endif %}
                    {{page.content|striptags|safe|truncatechars:"70"}}<br>
                    {{page.datetimecreation | date:'d-m-Y'}}
                    <a href={% url 'page_detail' page.id %}>mas info</a> |
                    <a href={% url 'page_delete' page.id %}>borrar</a> |
                    <a href={% url 'page_edit' page.id %}>Modificar</a>
                </li>
            </ul>
        {% endfor %}

        {% if not page_list %}
            <p style='color: #ff0000;'>¡No hay articulos creados!</p>
        {% endif %}
        
        </div>
    </div>
{% endblock body_block %}